$ErrorActionPreference = 'Stop'
$ScriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Definition

Write-Host "Installing Opure..."

# 1. Register the local self-signed dev certificate (generated by Opure.Packaging.Windows)
$CertPath = Join-Path $ScriptDirectory "artifacts\packaging\Opure.cer"
if (Test-Path $CertPath) {
    Write-Host "Registering dev certificate..."
    Import-Certificate -FilePath $CertPath -CertStoreLocation Cert:\CurrentUser\TrustedPeople
} else {
    Write-Host "Warning: Certificate not found at $CertPath. Ensure packaging step ran successfully." -ForegroundColor Yellow
}

# 2. Install the generated .msix
$MsixPath = Join-Path $ScriptDirectory "artifacts\packaging\Opure.msix"
if (Test-Path $MsixPath) {
    Write-Host "Installing MSIX package..."
    Add-AppxPackage -Path $MsixPath
} else {
    Write-Host "Warning: MSIX not found at $MsixPath. Please build it first." -ForegroundColor Yellow
}

# 3. Copy Opure.Cli.exe to %LOCALAPPDATA%\Opure\bin
$BinPath = Join-Path $env:LOCALAPPDATA "Opure\bin"
if (-not (Test-Path $BinPath)) {
    New-Item -ItemType Directory -Path $BinPath -Force | Out-Null
}

$CliSrcPath = Join-Path $ScriptDirectory "artifacts\publish\Opure.Cli"
if (Test-Path $CliSrcPath) {
    Write-Host "Copying CLI binaries to $BinPath..."
    Copy-Item -Path "$CliSrcPath\*" -Destination $BinPath -Recurse -Force
    
    # Pre-emptively add to User Path so `opure` command works if not there
    $UserPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($UserPath -notmatch [regex]::Escape($BinPath)) {
        Write-Host "Adding $BinPath to User PATH..."
        [Environment]::SetEnvironmentVariable("Path", "$UserPath;$BinPath", "User")
    }
} else {
    Write-Host "Warning: Opure.Cli publish folder not found at $CliSrcPath. Please publish the CLI first." -ForegroundColor Yellow
}

Write-Host "Installation complete." -ForegroundColor Green
