<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Filesystem\Opure.Filesystem.Contracts\Opure.Filesystem.Contracts.csproj" />
    <ProjectReference Include="..\..\Filesystem\Opure.Filesystem.Windows\Opure.Filesystem.Windows.csproj" />
    <ProjectReference Include="..\Opure.Workspace.Contracts\Opure.Workspace.Contracts.csproj" />
  </ItemGroup>

</Project>
