namespace Opure.Configuration.Contracts;

public static class FoundationSettingDefinitionCatalogue
{
    private static readonly DateTimeOffset CreatedAt =
        new(2026, 8, 3, 0, 0, 0, TimeSpan.Zero);

    public static SettingDefinitionCatalogue Current { get; } = new(
        catalogueRevision: 1,
        [
            CreateBoolean(
                "security.integrity-validation.enabled",
                "opure.runtime",
                "Integrity validation",
                "Keeps mandatory product integrity validation enabled.",
                defaultValue: true,
                [SettingScope.Product],
                [SettingSource.ProductDefault],
                SettingSensitivity.SecuritySensitive,
                SettingRuntimeApplication.NextApplicationStart,
                SettingRestartImpact.RestartApplication,
                SettingFailureClass.SecurityCritical,
                "security.integrity",
                order: 10),
            CreateEnumeration(
                "runtime.performance.default-mode",
                "opure.runtime",
                "Default performance mode",
                "Selects the default bounded resource posture for a new operation.",
                "balanced",
                ["eco", "balanced", "performance"],
                [SettingScope.User, SettingScope.Project, SettingScope.WorkspaceSession, SettingScope.Operation],
                [
                    SettingSource.ProductDefault,
                    SettingSource.UserBaseProfile,
                    SettingSource.NamedUserProfile,
                    SettingSource.ProjectSharedSettings,
                    SettingSource.ProjectLocalProfile,
                    SettingSource.WorkspaceSession,
                    SettingSource.SessionOverride,
                    SettingSource.OperationOverride
                ],
                SettingSensitivity.ProductInternal,
                SettingRuntimeApplication.NextOperation,
                SettingRestartImpact.None,
                SettingFailureClass.Operational,
                "runtime.performance",
                order: 20),
            CreateEnumeration(
                "logging.level.default",
                "opure.observability",
                "Default log level",
                "Sets the minimum safe operational log level for newly configured services.",
                "information",
                ["trace", "debug", "information", "warning", "error", "critical"],
                [SettingScope.Machine, SettingScope.User, SettingScope.Project, SettingScope.WorkspaceSession],
                [
                    SettingSource.ProductDefault,
                    SettingSource.ReleaseChannelDefault,
                    SettingSource.MachinePreference,
                    SettingSource.UserBaseProfile,
                    SettingSource.NamedUserProfile,
                    SettingSource.ProjectSharedSettings,
                    SettingSource.ProjectLocalProfile,
                    SettingSource.WorkspaceSession,
                    SettingSource.SessionOverride
                ],
                SettingSensitivity.ProductInternal,
                SettingRuntimeApplication.Immediate,
                SettingRestartImpact.ReconfigureService,
                SettingFailureClass.Operational,
                "observability.logging",
                order: 30),
            CreateEnumeration(
                "desktop.appearance.theme",
                "opure.desktop",
                "Theme",
                "Selects the developer-visible Desktop colour theme.",
                "system",
                ["system", "light", "dark"],
                [SettingScope.User, SettingScope.WorkspaceSession],
                [
                    SettingSource.ProductDefault,
                    SettingSource.UserBaseProfile,
                    SettingSource.NamedUserProfile,
                    SettingSource.WorkspaceSession,
                    SettingSource.SessionOverride
                ],
                SettingSensitivity.Public,
                SettingRuntimeApplication.Immediate,
                SettingRestartImpact.None,
                SettingFailureClass.Informational,
                "desktop.appearance",
                order: 40),
            CreateVaultReference()
        ]);

    private static SettingDefinition CreateBoolean(
        string id,
        string owner,
        string name,
        string description,
        bool defaultValue,
        SettingScope[] scopes,
        SettingSource[] sources,
        SettingSensitivity sensitivity,
        SettingRuntimeApplication application,
        SettingRestartImpact restart,
        SettingFailureClass failure,
        string category,
        int order) =>
        Create(
            id,
            owner,
            name,
            description,
            new SettingValueTypeDefinition(SettingValueKind.Boolean, 5),
            defaultValue ? "true" : "false",
            requiredFromSource: false,
            scopes,
            sources,
            sensitivity,
            SettingSecretPolicy.NoSecret,
            application,
            restart,
            failure,
            new SettingUiMetadata(category, "toggle", order));

    private static SettingDefinition CreateEnumeration(
        string id,
        string owner,
        string name,
        string description,
        string defaultValue,
        string[] values,
        SettingScope[] scopes,
        SettingSource[] sources,
        SettingSensitivity sensitivity,
        SettingRuntimeApplication application,
        SettingRestartImpact restart,
        SettingFailureClass failure,
        string category,
        int order) =>
        Create(
            id,
            owner,
            name,
            description,
            new SettingValueTypeDefinition(
                SettingValueKind.Enumeration,
                maximumEncodedBytes: 128,
                enumerationValues: values),
            System.Text.Json.JsonSerializer.Serialize(defaultValue),
            requiredFromSource: false,
            scopes,
            sources,
            sensitivity,
            SettingSecretPolicy.NoSecret,
            application,
            restart,
            failure,
            new SettingUiMetadata(category, "select", order));

    private static SettingDefinition CreateVaultReference() =>
        Create(
            "provider.credential.vault-reference",
            "opure.provider-trust",
            "Provider credential",
            "References a credential held by the Secrets Vault without storing its value.",
            new SettingValueTypeDefinition(SettingValueKind.VaultReference, 128),
            defaultValueJson: null,
            requiredFromSource: true,
            [SettingScope.User, SettingScope.Project, SettingScope.Provider],
            [SettingSource.UserBaseProfile, SettingSource.NamedUserProfile, SettingSource.ProjectLocalProfile],
            SettingSensitivity.SecretReference,
            SettingSecretPolicy.VaultReferenceRequired,
            SettingRuntimeApplication.NextOperation,
            SettingRestartImpact.None,
            SettingFailureClass.SecurityCritical,
            new SettingUiMetadata("providers.credentials", "vault-reference", 50, advanced: true));

    private static SettingDefinition Create(
        string id,
        string owner,
        string name,
        string description,
        SettingValueTypeDefinition valueType,
        string? defaultValueJson,
        bool requiredFromSource,
        SettingScope[] scopes,
        SettingSource[] sources,
        SettingSensitivity sensitivity,
        SettingSecretPolicy secretPolicy,
        SettingRuntimeApplication application,
        SettingRestartImpact restart,
        SettingFailureClass failure,
        SettingUiMetadata ui) =>
        new(
            id,
            revision: 1,
            owner,
            name,
            description,
            valueType,
            defaultValueJson,
            requiredFromSource,
            scopes,
            sources,
            SettingMergeStrategy.Replace,
            SettingNullSemantics.RejectNull,
            semanticValidatorIds: [],
            sensitivity,
            secretPolicy,
            policyDefinitionIds: [],
            application,
            restart,
            failure,
            ui,
            CreatedAt);
}
